[package]
name = "playground"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = { version = "0.8.7", features = ["derive"] }


[profile.release]
panic = "abort"
lto = true
opt-level = "s"
codegen-units = 1
